export const navItems = [
  { href: "/", label: "首页" },
  { href: "/#projects", label: "项目" },
  { href: "/#writing", label: "分享" },
  { href: "/#contact", label: "联系" },
];

export const categories = ["人工智能", "应用", "网站服务", "开源项目", "工具", "全部"];

export const projects = [
  {
    slug: "rizhuizong",
    title: "日追踪看板",
    githubUrl: "https://github.com/yxqhuqin222-star/rizhuizong",
    liveUrl: "https://rizhuizong.vercel.app",
    category: "网站服务",
    role: "主理人",
    status: "已上线",
    monogram: "日追踪",
    summary: "读取每日数据和目标数据，生成进度汇总、网页看板和学部播报图。",
    intro: "面向日常进度管理的看板项目，包含本地服务、看板页面、汇总计算、工作簿和播报图导出。",
    roleDescription: "负责需求整理、功能实现、部署和后续迭代。",
    tags: ["网站服务", "脚本工具", "已上线"],
    image: "/projects/rizhuizong.png",
    paragraphs: [
      "项目读取每日数据和每周目标数据，生成进度汇总、网页看板和学部播报图，并支持规则化的自然语言查询。",
      "这个项目把原本分散在表格、播报和统计里的操作整理成一条稳定流程，方便每天复用和复盘。",
    ],
  },
  {
    slug: "xiaoyuzhou-to-article-qwen",
    title: "小宇宙播客转文章",
    githubUrl: "https://github.com/yxqhuqin222-star/xiaoyuzhou-to-article-qwen",
    category: "人工智能",
    role: "开发者",
    status: "实验中",
    monogram: "播客",
    summary: "把小宇宙单集链接转成完整文字稿和结构化播客笔记。",
    intro: "输入小宇宙单集链接后，下载音频、转写内容、导出文稿，并按固定格式整理成播客笔记。",
    roleDescription: "负责流程设计、脚本实现和内容整理方式验证。",
    tags: ["人工智能", "自动化", "内容整理"],
    image: "/projects/xiaoyuzhou-to-article-qwen.png",
    paragraphs: [
      "完整流程是：输入小宇宙链接，下载原始音频，上传通义听悟转写，导出完整文字稿，检查开头、中段和结尾，最后生成结构化播客笔记。",
      "项目说明也明确标注：它不是阿里云、通义听悟或通义千问的官方项目；音频转写由通义听悟完成，内容整理由当前运行的模型执行。",
    ],
  },
  {
    slug: "dingtalk-broadcast-console",
    title: "钉钉播报控制台",
    githubUrl: "https://github.com/yxqhuqin222-star/dingtalk-broadcast-console",
    category: "工具",
    role: "开发者",
    status: "开发中",
    monogram: "播报",
    summary: "钉钉播报相关脚本和接口，包含预览、发送、定时播报和机器人消息客户端。",
    intro: "项目包含本地播报服务、预览和发送接口、定时脚本，以及钉钉机器人消息客户端。",
    roleDescription: "负责播报规则、消息结构和控制台功能实现。",
    tags: ["工具", "自动化", "播报"],
    image: "/projects/dingtalk-broadcast-console.png",
    paragraphs: [
      "项目提供消息预览和发送能力，可以先检查播报内容，再把消息发送到钉钉群。",
      "定时脚本包含早间、中午、行业、倒计时、晚间等播报类型，并内置多个默认发送时间。",
    ],
  },
  {
    slug: "pages_shouji",
    title: "碎片收集页",
    githubUrl: "https://github.com/yxqhuqin222-star/pages_shouji",
    category: "应用",
    role: "开发者",
    status: "实验中",
    monogram: "收集",
    summary: "给个人使用的轻量网页，用来快速收集碎片化信息，并按时间线查看、搜索和管理。",
    intro: "纯静态网页项目，支持内容保存、粘贴图片、时间线、搜索、标签筛选、编辑删除和备份导入导出。",
    roleDescription: "负责页面结构、展示方式和前端实现。",
    tags: ["应用", "前端页面", "信息收集"],
    image: "/projects/pages_shouji.png",
    paragraphs: [
      "功能包括：直接输入保存、粘贴图片保存、卡片流展示、搜索内容、识别标签、编辑删除记录、导出表格、导入导出备份。",
      "当前版本使用浏览器本地存储保存数据，不依赖服务器和数据库；适合个人快速记录和轻量整理。",
    ],
  },
  {
    slug: "feishu-chat-replay",
    title: "飞书聊天记录回放",
    githubUrl: "https://github.com/yxqhuqin222-star/feishu-chat-replay",
    category: "开源项目",
    role: "开发者",
    status: "实验中",
    monogram: "回放",
    summary: "本地聊天记录查看页面，用于复现飞书导出的聊天记录。",
    intro: "打开页面即可查看聊天记录，支持关键词搜索、高亮、日期筛选、发送人筛选和图片预览。",
    roleDescription: "负责记录结构、回放页面和前端展示实现。",
    tags: ["开源项目", "前端页面", "回放"],
    image: "/projects/feishu-chat-replay.png",
    paragraphs: [
      "功能包括：关键词搜索与高亮、上一条和下一条搜索结果跳转、日期范围筛选、发送人筛选、只看图片和表情、日期跳转、图片点击放大预览。",
      "它适合在本地复现导出的聊天记录，让搜索、筛选和图片查看更方便。",
    ],
  },
];

export const shares = [
  {
    title: "书籍",
    group: "书籍",
    summary: "读书笔记、摘录和读完之后真正留下来的想法。",
  },
  {
    title: "人工智能",
    group: "人工智能笔记",
    summary: "关于人工智能工具、自动化、智能代理和个人工作流的记录。",
  },
  {
    title: "效率与生活",
    group: "生活",
    summary: "把日常经验、复盘和一些小发现整理成可回看的分享。",
  },
];
