export const navItems = [
  { href: "/", label: "首页" },
  { href: "/#projects", label: "项目" },
  { href: "/#writing", label: "分享" },
  { href: "/#contact", label: "联系" },
];

export const categories = ["人工智能", "应用", "网站服务", "开源项目", "工具", "全部"];

export const projects = [
  {
    slug: "rizhuizong",
    title: "rizhuizong",
    githubUrl: "https://github.com/yxqhuqin222-star/rizhuizong",
    liveUrl: "https://rizhuizong.vercel.app",
    category: "网站服务",
    role: "主理人",
    status: "已上线",
    monogram: "RZ",
    summary: "读取 tongji_demo.xlsx 和 tongji_target.xlsx，生成进度汇总、网页看板和学部播报图。",
    intro: "日追踪看板项目，包含本地 HTTP 服务、看板前端、Summary 计算、工作簿和播报图导出。",
    roleDescription: "负责需求整理、功能实现、部署和后续迭代。",
    tags: ["网站服务", "Python", "已上线"],
    image: "/projects/rizhuizong.png",
    paragraphs: [
      "仓库 README 说明：项目读取每日 tongji_demo.xlsx 和每周 tongji_target.xlsx，生成进度汇总、网页看板和学部播报图，并支持规则化自然语言查询。",
      "仓库中的主要路径包括 app.py、web/、outputs/、reports/、config/、tests/、docs/、decisions/、source/ 和 rules/。",
    ],
  },
  {
    slug: "xiaoyuzhou-to-article-qwen",
    title: "xiaoyuzhou-to-article-qwen",
    githubUrl: "https://github.com/yxqhuqin222-star/xiaoyuzhou-to-article-qwen",
    category: "AI",
    role: "开发者",
    status: "实验中",
    monogram: "XA",
    summary: "把小宇宙单集链接转成完整文字稿和结构化 Markdown 播客笔记。",
    intro: "社区 skill 项目：下载小宇宙音频，上传通义听悟转写，导出文稿并按固定格式整理播客笔记。",
    roleDescription: "负责流程设计、脚本实现和内容整理方式验证。",
    tags: ["AI", "Shell", "内容"],
    image: "/projects/xiaoyuzhou-to-article-qwen.png",
    paragraphs: [
      "README 中确认的流程是：小宇宙链接、下载原始音频、上传通义听悟转写、导出完整文字稿、检查开头中段和结尾、生成结构化 Markdown 播客笔记。",
      "项目说明明确写到：它不是阿里云、通义听悟或 Qwen 官方项目；音频转写由通义听悟完成，内容整理由当前运行 skill 的模型执行。",
    ],
  },
  {
    slug: "dingtalk-broadcast-console",
    title: "dingtalk-broadcast-console",
    githubUrl: "https://github.com/yxqhuqin222-star/dingtalk-broadcast-console",
    category: "工具",
    role: "开发者",
    status: "开发中",
    monogram: "DB",
    summary: "钉钉播报相关脚本和接口，包含预览、发送、定时播报和 webhook 客户端。",
    intro: "仓库包含本地播报服务、Netlify 预览/发送接口、daily_broadcast 定时脚本和钉钉 webhook 客户端。",
    roleDescription: "负责播报规则、消息结构和控制台功能实现。",
    tags: ["工具", "Python", "自动化"],
    image: "/projects/dingtalk-broadcast-console.png",
    paragraphs: [
      "代码中可确认的接口包括 netlify/functions/preview.js 和 netlify/functions/broadcast.js，分别用于预览消息和调用 sendDingtalkMessage 发送到钉钉。",
      "jump/daily_broadcast.py 中包含 morning、noon、industry、countdown、evening 等播报类型，以及 10:00、11:40、16:30、17:30、19:00 的默认时间配置。",
    ],
  },
  {
    slug: "pages_shouji",
    title: "pages_shouji",
    githubUrl: "https://github.com/yxqhuqin222-star/pages_shouji",
    category: "应用",
    role: "开发者",
    status: "实验中",
    monogram: "PS",
    summary: "给个人使用的轻量网页，用来快速收集碎片化信息，并按时间线查看、搜索和管理。",
    intro: "纯静态网页项目，支持内容保存、粘贴图片、时间线、搜索、标签筛选、编辑删除和备份导入导出。",
    roleDescription: "负责页面结构、展示方式和前端实现。",
    tags: ["应用", "JavaScript", "页面"],
    image: "/projects/pages_shouji.png",
    paragraphs: [
      "README 中确认的功能包括：直接输入保存、粘贴图片保存、卡片流展示、搜索内容、识别 #标签、编辑删除记录、导出 Excel、导入导出 JSON 备份。",
      "当前版本使用浏览器 localStorage 保存数据，不依赖服务器和数据库；仓库中包含 preview-desktop.png 和 preview-mobile.png 两张真实预览图。",
    ],
  },
  {
    slug: "feishu-chat-replay",
    title: "feishu-chat-replay",
    githubUrl: "https://github.com/yxqhuqin222-star/feishu-chat-replay",
    category: "开源项目",
    role: "开发者",
    status: "实验中",
    monogram: "FR",
    summary: "本地 HTML 聊天记录查看页面，用于复现飞书导出的聊天记录。",
    intro: "打开 index.html 即可查看聊天记录，支持关键词搜索、高亮、日期筛选、发送人筛选和图片预览。",
    roleDescription: "负责记录结构、回放页面和前端展示实现。",
    tags: ["开源项目", "HTML", "回放"],
    image: "/projects/feishu-chat-replay.png",
    paragraphs: [
      "README 中确认的功能包括：关键词搜索与高亮、上一条/下一条搜索结果跳转、日期范围筛选、发送人筛选、只看图片/表情、日期跳转、图片点击放大预览。",
      "README 中的文件说明为：index.html 是聊天记录页面，messages.js 是解析后的聊天消息数据，chat-assets/ 是聊天中的图片和表情素材。",
    ],
  },
];

export const shares = [
  {
    title: "书籍",
    group: "书籍",
    summary: "读书笔记、摘录和读完之后真正留下来的想法。",
  },
  {
    title: "AI",
    group: "AI 笔记",
    summary: "关于 AI 工具、自动化、Agent 和个人工作流的记录。",
  },
  {
    title: "效率与生活",
    group: "生活",
    summary: "把日常经验、复盘和一些小发现整理成可回看的分享。",
  },
];
